In [2]:
import pandas as pd
import requests
import json

# Bootstrap response

In [15]:
bootstrap_API_response = requests.get('https://fantasy.premierleague.com/api/bootstrap-static/').json()

In [80]:
GWs_API_load_df = pd.DataFrame.from_dict(bootstrap_API_response['events'])
GWs_API_load_df

,id,name,deadline_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,highest_score,...,is_current,is_next,chip_plays,most_selected,most_transferred_in,top_element,top_element_info,transfers_made,most_captained,most_vice_captained
0,1,Gameweek 1,2021-08-13T17:30:00Z,69,True,True,5059647.0,1628875800,0,150.0,...,False,False,"[{'chip_name': 'bboost', 'num_played': 145658}...",275.0,1.0,277.0,"{'id': 277, 'points': 20}",0,233.0,277.0
1,2,Gameweek 2,2021-08-21T10:00:00Z,45,False,False,4497644.0,1629540000,0,120.0,...,True,False,"[{'chip_name': 'bboost', 'num_played': 95038},...",277.0,272.0,142.0,"{'id': 142, 'points': 18}",12038724,233.0,277.0
2,3,Gameweek 3,2021-08-28T10:00:00Z,0,False,False,NaN,1630144800,0,NaN,...,False,True,"[{'chip_name': 'bboost', 'num_played': 1539}, ...",NaN,NaN,NaN,None,46554,NaN,NaN
3,4,Gameweek 4,2021-09-11T10:00:00Z,0,False,False,NaN,1631354400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
4,5,Gameweek 5,2021-09-17T17:30:00Z,0,False,False,NaN,1631899800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
5,6,Gameweek 6,2021-09-25T10:00:00Z,0,False,False,NaN,1632564000,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
6,7,Gameweek 7,2021-10-02T10:00:00Z,0,False,False,NaN,1633168800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
7,8,Gameweek 8,2021-10-16T10:00:00Z,0,False,False,NaN,1634378400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
8,9,Gameweek 9,2021-10-22T17:30:00Z,0,False,False,NaN,1634923800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
9,10,Gameweek 10,2021-10-30T10:00:00Z,0,False,False,NaN,1635588000,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
10,11,Gameweek 11,2021-11-06T13:30:00Z,0,False,False,NaN,1636205400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
11,12,Gameweek 12,2021-11-20T13:30:00Z,0,False,False,NaN,1637415000,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
12,13,Gameweek 13,2021-11-27T13:30:00Z,0,False,False,NaN,1638019800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
13,14,Gameweek 14,2021-11-30T18:15:00Z,0,False,False,NaN,1638296100,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
14,15,Gameweek 15,2021-12-04T13:30:00Z,0,False,False,NaN,1638624600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
15,16,Gameweek 16,2021-12-11T13:30:00Z,0,False,False,NaN,1639229400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
16,17,Gameweek 17,2021-12-14T18:15:00Z,0,False,False,NaN,1639505700,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
17,18,Gameweek 18,2021-12-18T13:30:00Z,0,False,False,NaN,1639834200,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
18,19,Gameweek 19,2021-12-26T13:30:00Z,0,False,False,NaN,1640525400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
19,20,Gameweek 20,2021-12-28T13:30:00Z,0,False,False,NaN,1640698200,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
20,21,Gameweek 21,2022-01-01T13:30:00Z,0,False,False,NaN,1641043800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
21,22,Gameweek 22,2022-01-15T13:30:00Z,0,False,False,NaN,1642253400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
22,23,Gameweek 23,2022-01-22T13:30:00Z,0,False,False,NaN,1642858200,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
23,24,Gameweek 24,2022-02-08T18:15:00Z,0,False,False,NaN,1644344100,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
24,25,Gameweek 25,2022-02-12T13:30:00Z,0,False,False,NaN,1644672600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
25,26,Gameweek 26,2022-02-19T13:30:00Z,0,False,False,NaN,1645277400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
26,27,Gameweek 27,2022-02-26T13:30:00Z,0,False,False,NaN,1645882200,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
27,28,Gameweek 28,2022-03-05T13:30:00Z,0,False,False,NaN,1646487000,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
28,29,Gameweek 29,2022-03-12T13:30:00Z,0,False,False,NaN,1647091800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
29,30,Gameweek 30,2022-03-19T13:30:00Z,0,False,False,NaN,1647696600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
30,31,Gameweek 31,2022-04-02T12:30:00Z,0,False,False,NaN,1648902600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
31,32,Gameweek 32,2022-04-09T12:30:00Z,0,False,False,NaN,1649507400,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
32,33,Gameweek 33,2022-04-16T12:30:00Z,0,False,False,NaN,1650112200,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
33,34,Gameweek 34,2022-04-23T12:30:00Z,0,False,False,NaN,1650717000,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
34,35,Gameweek 35,2022-04-30T12:30:00Z,0,False,False,NaN,1651321800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
35,36,Gameweek 36,2022-05-07T12:30:00Z,0,False,False,NaN,1651926600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
36,37,Gameweek 37,2022-05-15T12:30:00Z,0,False,False,NaN,1652617800,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN
37,38,Gameweek 38,2022-05-22T12:30:00Z,0,False,False,NaN,1653222600,0,NaN,...,False,False,[],NaN,NaN,NaN,None,0,NaN,NaN

In [46]:
teams_API_load_df = pd.DataFrame.from_dict(bootstrap_API_response['teams'])
teams_API_load_df.head()

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,0,ARS,...,None,False,0,1200,1250,1130,1150,1220,1210,1
1,7,0,None,2,0,Aston Villa,0,0,0,AVL,...,None,False,0,1100,1160,1120,1140,1080,1100,2
2,94,0,None,3,0,Brentford,0,0,0,BRE,...,None,False,0,1010,1020,1020,1030,1020,1030,130
3,36,0,None,4,0,Brighton,0,0,0,BHA,...,None,False,0,1100,1130,1150,1190,1100,1130,131
4,90,0,None,5,0,Burnley,0,0,0,BUR,...,None,False,0,1060,1070,1040,1090,1040,1080,43

In [47]:
elements_API_load_df = pd.DataFrame.from_dict(bootstrap_API_response['elements'])
elements_API_load_df

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,NaN,NaN,80201,0,0,0,0,0,1,1.0,...,443,49,200,12,NaN,,NaN,,NaN,
1,0.0,0.0,115918,0,0,0,0,0,1,0.0,...,256,10,327,30,NaN,,NaN,,NaN,
2,50.0,50.0,47431,0,0,-1,1,0,3,-0.2,...,552,230,554,231,4.0,,2.0,,NaN,
3,100.0,50.0,54694,0,0,-1,1,0,4,0.0,...,113,28,235,32,NaN,,NaN,,1.0,
4,NaN,NaN,58822,0,0,0,0,0,2,0.0,...,309,116,192,66,NaN,,5.0,,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
561,NaN,NaN,149065,0,0,0,0,0,1,2.5,...,460,53,137,5,NaN,,NaN,,NaN,
562,0.0,0.0,209353,0,0,0,0,0,4,0.0,...,475,54,496,57,NaN,,NaN,,NaN,
563,NaN,NaN,245923,0,0,0,0,0,3,-0.5,...,402,157,443,171,NaN,,NaN,,NaN,
564,NaN,NaN,461026,0,0,0,0,0,3,-0.5,...,412,163,452,176,NaN,,NaN,,NaN,
565,NaN,NaN,481626,0,0,0,0,0,2,-0.5,...,283,103,351,127,NaN,,NaN,,NaN,

In [ ]:
elements_API_load_df[['first_name',
                      'second_name',
                      'id',
                      'chance_of_playing_next_round',
                      'element_type',
                      'news',
                      'now_cost',
                      'status',
                      'team']]

In [ ]:
elements_API_load_df

In [40]:
positions_API_load_df = pd.DataFrame.from_dict(bootstrap_API_response['element_types'])
positions_API_load_df

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,1,1,True,[12],60
1,2,Defenders,DEF,Defender,DEF,5,3,5,False,[],194
2,3,Midfielders,MID,Midfielder,MID,5,2,5,False,[],236
3,4,Forwards,FWD,Forward,FWD,3,1,3,False,[],76

# Fixtures response

In [52]:
fixtures_API_response = requests.get('https://fantasy.premierleague.com/api/fixtures/').json()
fixtures_API_load_df = pd.DataFrame.from_dict(fixtures_API_response)
fixtures_API_load_df.head()

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,66347
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,66343
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,4,66344
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,3,66345

In [81]:
fixtures_API_load_df[['event',
                      'kickoff_time',
                      'team_a',
                      'team_h',]]

,code,event,finished,finished_provisional,id,kickoff_time,minutes,provisional_start_time,started,team_a,team_a_score,team_h,team_h_score,stats,team_h_difficulty,team_a_difficulty,pulse_id
0,2210271,1,True,True,1,2021-08-13T19:00:00Z,90,False,True,1,0.0,3,2.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",3,2,66342
1,2210276,1,True,True,6,2021-08-14T11:30:00Z,90,False,True,10,1.0,13,5.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",3,4,66347
2,2210272,1,True,True,2,2021-08-14T14:00:00Z,90,False,True,4,2.0,5,1.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,2,66343
3,2210273,1,True,True,3,2021-08-14T14:00:00Z,90,False,True,7,0.0,6,3.0,"[{'identifier': 'goals_scored', 'a': [], 'h': ...",2,4,66344
4,2210274,1,True,True,4,2021-08-14T14:00:00Z,90,False,True,16,1.0,8,3.0,"[{'identifier': 'goals_scored', 'a': [{'value'...",2,3,66345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2210646,38,False,False,376,2022-05-22T15:00:00Z,0,False,False,13,NaN,7,NaN,[],4,2,66717
376,2210647,38,False,False,377,2022-05-22T15:00:00Z,0,False,False,16,NaN,9,NaN,[],2,3,66718
377,2210648,38,False,False,378,2022-05-22T15:00:00Z,0,False,False,20,NaN,11,NaN,[],2,4,66719
378,2210649,38,False,False,379,2022-05-22T15:00:00Z,0,False,False,2,NaN,12,NaN,[],2,5,66720
379,2210650,38,False,False,380,2022-05-22T15:00:00Z,0,False,False,17,NaN,15,NaN,[],3,2,66721

# Matches data

In [82]:
matches_API_response = requests.get('https://fantasy.premierleague.com/api/element-summary/43/').json()

upcoming_matches = pd.DataFrame.from_dict(matches_API_response['fixtures'])
upcoming_matches

,id,code,team_h,team_h_score,team_a,team_a_score,event,finished,minutes,provisional_start_time,kickoff_time,event_name,is_home,difficulty
0,21,2210291,2,None,3,None,3,False,0,False,2021-08-28T14:00:00Z,Gameweek 3,True,2
1,33,2210303,6,None,2,None,4,False,0,False,2021-09-11T16:30:00Z,Gameweek 4,False,4
2,41,2210311,2,None,8,None,5,False,0,False,2021-09-18T16:30:00Z,Gameweek 5,True,4
3,58,2210328,13,None,2,None,6,False,0,False,2021-09-25T14:00:00Z,Gameweek 6,False,4
4,68,2210338,17,None,2,None,7,False,0,False,2021-10-02T14:00:00Z,Gameweek 7,False,4
5,72,2210342,2,None,20,None,8,False,0,False,2021-10-16T14:00:00Z,Gameweek 8,True,2
6,81,2210351,1,None,2,None,9,False,0,False,2021-10-22T19:00:00Z,Gameweek 9,False,4
7,91,2210361,2,None,19,None,10,False,0,False,2021-10-31T16:30:00Z,Gameweek 10,True,3
8,109,2210379,16,None,2,None,11,False,0,False,2021-11-06T15:00:00Z,Gameweek 11,False,2
9,111,2210381,2,None,4,None,12,False,0,False,2021-11-20T15:00:00Z,Gameweek 12,True,2
10,126,2210396,7,None,2,None,13,False,0,False,2021-11-27T15:00:00Z,Gameweek 13,False,2
11,131,2210401,2,None,12,None,14,False,0,False,2021-11-30T19:45:00Z,Gameweek 14,True,4
12,141,2210411,2,None,9,None,15,False,0,False,2021-12-04T15:00:00Z,Gameweek 15,True,4
13,158,2210428,11,None,2,None,16,False,0,False,2021-12-11T15:00:00Z,Gameweek 16,False,4
14,167,2210437,15,None,2,None,17,False,0,False,2021-12-14T19:45:00Z,Gameweek 17,False,2
15,171,2210441,2,None,5,None,18,False,0,False,2021-12-18T15:00:00Z,Gameweek 18,True,2
16,181,2210451,2,None,6,None,19,False,0,False,2021-12-26T15:00:00Z,Gameweek 19,True,4
17,196,2210466,10,None,2,None,20,False,0,False,2021-12-28T15:00:00Z,Gameweek 20,False,3
18,202,2210472,3,None,2,None,21,False,0,False,2022-01-01T15:00:00Z,Gameweek 21,False,2
19,211,2210481,2,None,13,None,22,False,0,False,2022-01-15T15:00:00Z,Gameweek 22,True,4
20,225,2210495,8,None,2,None,23,False,0,False,2022-01-22T15:00:00Z,Gameweek 23,False,3
21,231,2210501,2,None,10,None,24,False,0,False,2022-02-08T19:45:00Z,Gameweek 24,True,3
22,247,2210517,14,None,2,None,25,False,0,False,2022-02-12T15:00:00Z,Gameweek 25,False,2
23,252,2210522,2,None,18,None,26,False,0,False,2022-02-19T15:00:00Z,Gameweek 26,True,2
24,263,2210533,4,None,2,None,27,False,0,False,2022-02-26T15:00:00Z,Gameweek 27,False,3
25,271,2210541,2,None,16,None,28,False,0,False,2022-03-05T15:00:00Z,Gameweek 28,True,2
26,290,2210560,19,None,2,None,29,False,0,False,2022-03-12T15:00:00Z,Gameweek 29,False,4
27,291,2210561,2,None,1,None,30,False,0,False,2022-03-19T15:00:00Z,Gameweek 30,True,3
28,310,2210580,20,None,2,None,31,False,0,False,2022-04-02T14:00:00Z,Gameweek 31,False,3
29,312,2210582,2,None,17,None,32,False,0,False,2022-04-09T14:00:00Z,Gameweek 32,True,3
30,321,2210591,2,None,11,None,33,False,0,False,2022-04-16T14:00:00Z,Gameweek 33,True,4
31,337,2210607,9,None,2,None,34,False,0,False,2022-04-23T14:00:00Z,Gameweek 34,False,3
32,341,2210611,2,None,15,None,35,False,0,False,2022-04-30T14:00:00Z,Gameweek 35,True,2
33,354,2210624,5,None,2,None,36,False,0,False,2022-05-07T14:00:00Z,Gameweek 36,False,2
34,361,2210631,2,None,7,None,37,False,0,False,2022-05-15T14:00:00Z,Gameweek 37,True,2
35,379,2210649,12,None,2,None,38,False,0,False,2022-05-22T15:00:00Z,Gameweek 38,False,5

In [83]:
previous_matches = pd.DataFrame.from_dict(matches_API_response['history'])
previous_matches

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,minutes,...,bps,influence,creativity,threat,ict_index,value,transfers_balance,selected,transfers_in,transfers_out
0,43,8,18,2,False,2021-08-14T14:00:00Z,3,2,1,71,...,6,4.2,5.3,10.0,2.0,65,0,386824,0,0
1,43,11,14,2,True,2021-08-21T14:00:00Z,2,0,2,85,...,6,11.6,36.2,2.0,5.0,65,-31772,374696,20786,52558

In [3]:
matches_API_response = requests.get('https://fantasy.premierleague.com/api/element-summary/81/').json()
pd.DataFrame.from_dict(matches_API_response['history_past'])

,season_name,element_code,start_cost,end_cost,total_points,minutes,goals_scored,assists,clean_sheets,goals_conceded,...,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index
0,2015/16,174932,45,45,1,10,0,0,0,0,...,0,0,0,0,0,2,0.0,0.0,0.0,0.0